name: Keep Replit Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Keep Replit Alive
        run: |
          curl -s https://replit.com/@lukegoat42/YouthfulDistinctMemory > /dev/null
