name: Keep Replit Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Keep Replit Alive
        run: |
          curl -s https://446bb411-eca4-4f2b-8e7f-766dc6504a0b-00-3s9lhh9t6f0zm.riker.replit.dev/ > /dev/null
